#! /usr/bin/env python3

# -*- coding: utf-8 -*-

""" 
Description:
  Auto Generate G-Code for milling a 
  outside full radius for corn hole legs
  this could be used for any outside full radius (grbl 1.1 control)
Programmer: Troy Franks
Email: outlaws42@tutanota.com
"""
version = '2021-04-17'

# Requires tmod library. This is a collection of my functions, 
# it will be included with this script
# All other imports are standard with python 3.

# User script imports
from tmod import save_file_list

# python built in imports
import sys
import os
from datetime import datetime

# Variable set information
# Cut information

materialWidth = 3.5 # Width of the part
radius = materialWidth/2 # radius of the part
tool_dia = .250 # Diameter of the tool in inches
feed = 70. # Feedrate for horizontal moves in inches/min
rFeed = 50. # Feedrate for radius moves in inches/min
zFeed = 20. # Feedrate for z moves in inches/min
zDepth = .05 # Step down for each pass
thickness = .750 # Part thickess
status = 'Proven' # Proven or Unproven
outputFile = f"CH_RADIUS-Feed{feed}-{radius}X{materialWidth}-{status}.gcode"

# Header information description
x_zero = 'CENTER OF HOLE LOCATION'
y_zero = 'CENTER OF HOLE LOCATION '
z_zero = 'TOP OF WORK PIECE'
material = f'{thickness}" WOOD'
tool = f'{tool_dia}" CARBIDE ENDMILL'

def header(x_zero,y_zero,z_zero,material,tool,status):
  dateset = datetime.now().strftime("%Y/%m/%d, %H:%M")
  filename = os.path.basename(sys.argv[0])
  output = (
    f"%\n"
    f"(CUT OUT HANDLE)\n"
    f"(WRITTEN FOR GRBL CONTROL)\n"
    f"(THIS PROGRAM WAS GENERATED BY {filename})\n"
    f"(DATE: {dateset})\n\n" 
    f"( *** {status.upper()} PROGRAM *** )\n\n"
    f"(MAKE SURE TO SET G28 WITH G28.1 RETRACTED TO TOP POSITION )\n\n"
    f"( SETUP INFORMATION )\n"
    f"( ZERO SET INFORMATION )\n"
    f"(X0 = {x_zero})\n"
    f"(Y0 = {y_zero})\n"
    f"(Z0 = {z_zero})\n\n"
    f"(MATERIAL TYPE= {material})\n"
    f"(TOOL= {tool})\n\n"
    )
  return output

def initialization():
  output = (
    f"G20 (SET CODE TO INCH)\n"
    f"G17 (XY PLANE SELECTION)\n"
    f"G28 G91 Z0 (SEND TO RETURN POS.)\n"
    f"G90 (ABSOLUTE POSITION)\n"
    f"G54 (WORK CORD)\n"
    f"G94 (INCHES PER MINUTE)\n"
  )
  return output

def start():
  output = (
    f"G0 Z1.0\n"
  )
  return output

def operation(materialWidth,tool_dia,feed,zFeed, rFeed, thickness,zDepth):
  r_move = round(((materialWidth/2) + (tool_dia/2)),3)
  y_move = round(((materialWidth/2) + (tool_dia/2)),3)
  x_move = round(((materialWidth/2) + (tool_dia/2)),3)
  z_clear = .100
  zStep = 0
  zPos = zStep
  partThickness = thickness + .001
  passes = 1
  codePass = []
  while zStep <= partThickness:
    output = (
      f"\n(PASSES {passes})\n"
      f"G01 G90 X0 Y-{y_move + .100} F{feed}\n"
      f"G01 Z-{zPos} F{zFeed}\n"
      f"G01 Y-{y_move} F{feed}\n"
      f"G02 X-{x_move} Y0 R{r_move} F{rFeed}\n"
      f"G02 X0 Y{y_move} R{r_move} F{rFeed}\n"
      f"G01 Y{y_move + .10} F{feed}\n"
      f"G01 Z{z_clear} F{zFeed}\n"
    )
    zStep += zDepth
    zPos = '%.3f' % round(zStep, 3) # Round to 3 decimal places
    passes += 1
    codePass.append(output)
  codeOutput = ''.join(codePass)
  return codeOutput

def final_pass(materialWidth,tool_dia,feed,zFeed, rFeed, thickness):
  r_move = round(((materialWidth/2) + (tool_dia/2)),3)
  y_move = round(((materialWidth/2) + (tool_dia/2)),3)
  x_move = round(((materialWidth/2) + (tool_dia/2)),3)
  z_clear = .100
  output = (
      f"\n(FINAL PASS)\n"
      f"G01 G90 X0 Y-{y_move + .100} F{feed}\n"
      f"G01 Z-{thickness} F{zFeed}\n"
      f"G01 Y-{y_move} F{feed}\n"
      f"G02 X-{x_move} Y0 R{r_move} F{rFeed}\n"
      f"G02 X0 Y{y_move} R{r_move} F{rFeed}\n"
      f"G01 Y{y_move + .10} F{feed}\n"
      f"G01 Z{z_clear} F{zFeed}\n"
    )
  return output

def end():
  output = (
    f"G28 G91 Z0\n"
    f"G0 G90 X0 Y0\n"
    f"M2\n"
    f"M30\n"
    f"%"
    )
  return output   

setHeader = header(x_zero,y_zero,z_zero,material,tool,status)
setInitialization = initialization()
setStart = start()
setOperation = operation(materialWidth,tool_dia,feed, zFeed, rFeed,thickness,zDepth)
set_final = final_pass(materialWidth,tool_dia,feed, zFeed, rFeed,thickness)
setEnd = end()
programCNC = [setHeader, setInitialization, setStart, setOperation, set_final, setEnd]
save_file_list(outputFile,programCNC,'relative')